dbt_nyc:
  outputs:
    dev:
      dataset: nyc_models
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dbt-bq-public-datasets
      threads: 16
      type: bigquery
  target: dev
